# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftCode' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	pod 'Alamofire', '~> 4.2.0'
	# Pods for swiftCode

end
